# Generated by Django 2.1.7 on 2019-05-01 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_favtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='favtable',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
